from typing import Any, Dict, List

class Environment:
    def set_near(self, account_id: str = ..., private_key: str = ..., rpc_addr: str = ...) -> Any: ...
    def get_tool_registry(self) -> Any: ...
    def add_reply(self, message: str) -> None: ...
    def query_vector_store(self, vs_id: str, user_query: str) -> List[Dict[str, Any]]: ...
    def get_logger(self) -> Any: ...
    def list_messages(self) -> List[Dict[str, Any]]: ...
    def completions_and_run_tools(self, prompt_list: List[Dict[str, Any]], *, tools: List[Any]) -> None: ...
